drop extension if exists "pg_net";

create extension if not exists "vector" with schema "public";


  create table "public"."profiles" (
    "id" uuid not null,
    "email" text,
    "full_name" text,
    "credits_remaining" integer not null default 0,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now()
      );


alter table "public"."profiles" enable row level security;


  create table "public"."reef_papers" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "title" text,
    "abstract" text,
    "authors" text,
    "publish_date" date,
    "doi" text,
    "journal_ref" text,
    "embedding" public.vector(1536)
      );


alter table "public"."reef_papers" enable row level security;


  create table "public"."reef_searches" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid not null default auth.uid(),
    "embedding" public.vector,
    "title" text default 'Untitled'::text
      );


alter table "public"."reef_searches" enable row level security;

CREATE UNIQUE INDEX papers_pkey ON public.reef_papers USING btree (id);

CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id);

CREATE INDEX reef_papers_embedding_idx ON public.reef_papers USING hnsw (embedding public.vector_cosine_ops);

CREATE UNIQUE INDEX reef_searches_pkey ON public.reef_searches USING btree (id);

alter table "public"."profiles" add constraint "profiles_pkey" PRIMARY KEY using index "profiles_pkey";

alter table "public"."reef_papers" add constraint "papers_pkey" PRIMARY KEY using index "papers_pkey";

alter table "public"."reef_searches" add constraint "reef_searches_pkey" PRIMARY KEY using index "reef_searches_pkey";

alter table "public"."profiles" add constraint "profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."profiles" validate constraint "profiles_id_fkey";

alter table "public"."reef_searches" add constraint "reef_searches_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."reef_searches" validate constraint "reef_searches_user_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  INSERT INTO public.profiles (id, email, full_name)
  VALUES (
    new.id,
    new.email,
    new.raw_user_meta_data->>'full_name'
  );
  RETURN new;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.match_papers(query_embedding public.vector, match_threshold double precision DEFAULT 0.5, match_count integer DEFAULT 10)
 RETURNS TABLE(id bigint, title text, abstract text, authors text, publish_date date, doi text, journal_ref text, similarity double precision)
 LANGUAGE sql
 STABLE
AS $function$
  select
    reef_papers.id,
    reef_papers.title,
    reef_papers.abstract,
    reef_papers.authors,
    reef_papers.publish_date,
    reef_papers.doi,
    reef_papers.journal_ref,
    1 - (reef_papers.embedding <=> query_embedding) as similarity
  from reef_papers
  where 1 - (reef_papers.embedding <=> query_embedding) > match_threshold
  order by reef_papers.embedding <=> query_embedding
  limit match_count;
$function$
;

CREATE OR REPLACE FUNCTION public.update_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  new.updated_at = now();
  return new;
end;
$function$
;

grant delete on table "public"."profiles" to "anon";

grant insert on table "public"."profiles" to "anon";

grant references on table "public"."profiles" to "anon";

grant select on table "public"."profiles" to "anon";

grant trigger on table "public"."profiles" to "anon";

grant truncate on table "public"."profiles" to "anon";

grant update on table "public"."profiles" to "anon";

grant delete on table "public"."profiles" to "authenticated";

grant insert on table "public"."profiles" to "authenticated";

grant references on table "public"."profiles" to "authenticated";

grant select on table "public"."profiles" to "authenticated";

grant trigger on table "public"."profiles" to "authenticated";

grant truncate on table "public"."profiles" to "authenticated";

grant update on table "public"."profiles" to "authenticated";

grant delete on table "public"."profiles" to "service_role";

grant insert on table "public"."profiles" to "service_role";

grant references on table "public"."profiles" to "service_role";

grant select on table "public"."profiles" to "service_role";

grant trigger on table "public"."profiles" to "service_role";

grant truncate on table "public"."profiles" to "service_role";

grant update on table "public"."profiles" to "service_role";

grant delete on table "public"."reef_papers" to "anon";

grant insert on table "public"."reef_papers" to "anon";

grant references on table "public"."reef_papers" to "anon";

grant select on table "public"."reef_papers" to "anon";

grant trigger on table "public"."reef_papers" to "anon";

grant truncate on table "public"."reef_papers" to "anon";

grant update on table "public"."reef_papers" to "anon";

grant delete on table "public"."reef_papers" to "authenticated";

grant insert on table "public"."reef_papers" to "authenticated";

grant references on table "public"."reef_papers" to "authenticated";

grant select on table "public"."reef_papers" to "authenticated";

grant trigger on table "public"."reef_papers" to "authenticated";

grant truncate on table "public"."reef_papers" to "authenticated";

grant update on table "public"."reef_papers" to "authenticated";

grant delete on table "public"."reef_papers" to "service_role";

grant insert on table "public"."reef_papers" to "service_role";

grant references on table "public"."reef_papers" to "service_role";

grant select on table "public"."reef_papers" to "service_role";

grant trigger on table "public"."reef_papers" to "service_role";

grant truncate on table "public"."reef_papers" to "service_role";

grant update on table "public"."reef_papers" to "service_role";

grant delete on table "public"."reef_searches" to "anon";

grant insert on table "public"."reef_searches" to "anon";

grant references on table "public"."reef_searches" to "anon";

grant select on table "public"."reef_searches" to "anon";

grant trigger on table "public"."reef_searches" to "anon";

grant truncate on table "public"."reef_searches" to "anon";

grant update on table "public"."reef_searches" to "anon";

grant delete on table "public"."reef_searches" to "authenticated";

grant insert on table "public"."reef_searches" to "authenticated";

grant references on table "public"."reef_searches" to "authenticated";

grant select on table "public"."reef_searches" to "authenticated";

grant trigger on table "public"."reef_searches" to "authenticated";

grant truncate on table "public"."reef_searches" to "authenticated";

grant update on table "public"."reef_searches" to "authenticated";

grant delete on table "public"."reef_searches" to "service_role";

grant insert on table "public"."reef_searches" to "service_role";

grant references on table "public"."reef_searches" to "service_role";

grant select on table "public"."reef_searches" to "service_role";

grant trigger on table "public"."reef_searches" to "service_role";

grant truncate on table "public"."reef_searches" to "service_role";

grant update on table "public"."reef_searches" to "service_role";


  create policy "Users can update own profile"
  on "public"."profiles"
  as permissive
  for update
  to public
using ((auth.uid() = id));



  create policy "Users can view own profile"
  on "public"."profiles"
  as permissive
  for select
  to public
using ((auth.uid() = id));



  create policy "Enable read access for all users"
  on "public"."reef_papers"
  as permissive
  for select
  to public
using (true);


CREATE TRIGGER profiles_updated_at BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();

CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


